// Generated by CoffeeScript 1.4.0
(function() {
  var childproc, everyone, fs, path, request, sh, util,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  everyone = process.everyone;

  fs = require('fs');

  util = require('util');

  childproc = require('child_process');

  sh = require('shelljs');

  request = require('request');

  path = require('path');

  everyone.now.getWidgetData = function(name, callback) {
    var data, pckg;
    try {
      if (path.existsSync("components/" + name + "/package.json")) {
        pckg = fs.readFileSync("components/" + name + "/package.json", 'utf8');
      } else {
        pckg = '';
      }
      data = {
        name: name,
        browser: fs.readFileSync("components/" + name + "/js/" + name + ".coffee", 'utf8'),
        nodejs: fs.readFileSync("components/" + name + "/" + name + ".coffee", 'utf8'),
        js: fs.readFileSync("components/" + name + "/js/" + name + ".js", 'utf8'),
        html: fs.readFileSync("components/" + name + "/" + name + ".html", 'utf8'),
        css: fs.readFileSync("components/" + name + "/css/" + name + ".css", 'utf8'),
        scripts: fs.readFileSync("components/" + name + "/scripts", 'utf8'),
        styles: fs.readFileSync("components/" + name + "/styles", 'utf8'),
        pckg: pckg
      };
      return callback(data);
    } catch (e) {
      console.log(e);
      return callback(null, e);
    }
  };

  everyone.now.saveWidgetData = function(data, callback) {
    var name, waitforinstall;
    console.log(util.inspect(data));
    name = data.name;
    fs.writeFileSync("components/" + name + "/js/" + name + ".coffee", data.browser, 'utf8');
    fs.writeFileSync("components/" + name + "/" + name + ".coffee", data.nodejs, 'utf8');
    fs.writeFileSync("components/" + name + "/css/" + name + ".css", data.css, 'utf8');
    fs.writeFileSync("components/" + name + "/" + name + ".html", data.html, 'utf8');
    if ((data.pckg != null) && data.pckg !== '') {
      fs.writeFileSync("components/" + name + "/package.json", data.pckg, 'utf8');
    } else {
      console.log('data.pckg was undefined/black');
    }
    waitforinstall = false;
    if (data.pckg !== '') {
      console.log('executing npm install');
      waitforinstall = true;
      childproc.exec("cd components/" + name + ";npm install", function(er, o, e) {
        var oe;
        if (er != null) {
          console.log(er);
        }
        oe = o + e;
        console.log(oe);
        if (oe.indexOf('ERR') >= 0) {
          return callback(o + "\n" + e);
        } else {
          return callback("");
        }
      });
    } else {
      console.log('package is blank not executing');
    }
    childproc.exec("coffee -o components/" + name + "/js -c components/" + name + "/js/" + name + ".coffee", function(er, o, e) {
      return childproc.exec("coffee -o /tmp -c components/" + name + "/" + name + ".coffee", function(er, o2, e2) {
        if (!waitforinstall) {
          return callback(o + "\n" + e + "\n" + o2 + "\n" + e2);
        }
      });
    });
    fs.writeFileSync("components/" + name + "/scripts", data.scripts, 'utf8');
    return fs.writeFileSync("components/" + name + "/styles", data.styles, 'utf8');
  };

  everyone.now.listComponents = function(callback) {
    var active;
    active = process.listfile('loadorder');
    return fs.readdir('components', function(err, dirs) {
      var comp, dir, ret, _i, _j, _len, _len1;
      ret = [];
      for (_i = 0, _len = active.length; _i < _len; _i++) {
        comp = active[_i];
        ret.push({
          name: comp,
          active: true
        });
      }
      for (_j = 0, _len1 = dirs.length; _j < _len1; _j++) {
        dir = dirs[_j];
        if (!(__indexOf.call(active, dir) >= 0)) {
          ret.push({
            name: dir,
            active: (__indexOf.call(active, dir) >= 0)
          });
        }
      }
      return callback(ret);
    });
  };

  everyone.now.setActiveComponents = function(list, callback) {
    var str;
    str = list.join('\n');
    return fs.writeFile('loadorder', str, 'utf8', function(err) {
      if (callback != null) {
        return callback(err);
      }
    });
  };

  everyone.now.deleteComponent = function(name, callback) {
    try {
      sh.rm('-Rf', "components/" + name);
      return callback(true);
    } catch (e) {
      return callback(false, err);
    }
  };

  everyone.now.copyComponent = function(name, callback) {
    var n, newname, numarr, scripts, styles;
    n = 1;
    numarr = name.match(/[0-9]+$/m);
    if (numarr != null) {
      n = numarr[0] + 1;
    }
    newname = name + (n.toString());
    sh.mkdir('-p', "components/" + newname);
    sh.cp('-R', "components/" + name + "/*", "components/" + newname);
    fs.rename("components/" + newname + "/" + name + ".coffee", "components/" + newname + "/" + newname + ".coffee");
    fs.rename("components/" + newname + "/" + name + ".html", "components/" + newname + "/" + newname + ".html");
    fs.rename("components/" + newname + "/css/" + name + ".css", "components/" + newname + "/css/" + newname + ".css");
    scripts = fs.readFile("components/" + newname + "/scripts", 'utf8', function(err, data) {
      scripts = data.replace("" + name + ".js", "" + newname + ".js");
      return fs.writeFile("components/" + newname + "/scripts", scripts, 'utf8');
    });
    styles = fs.readFile("components/" + newname + "/styles", 'utf8', function(err, data) {
      styles = data.replace("" + name + ".css", "" + newname + ".css");
      return fs.writeFile("components/" + newname + "/styles", styles, 'utf8');
    });
    return fs.rename("components/" + newname + "/js/" + name + ".coffee", "components/" + newname + "/js/" + newname + ".coffee", function(err) {
      if (!(err != null)) {
        return childproc.exec("coffee -o components/" + newname + "/js -c components/" + newname + "/js/" + newname + ".coffee", function(er, o, e) {
          return callback(true);
        });
      } else {
        return callback(false, err);
      }
    });
  };

  everyone.now.renameComponent = function(name, newname, callback) {
    var scripts, styles;
    console.log('received rename for ' + name + ' to ' + newname);
    fs.rename("components/" + name + "/" + name + ".coffee", "components/" + name + "/" + newname + ".coffee");
    fs.rename("components/" + name + "/" + name + ".html", "components/" + name + "/" + newname + ".html");
    fs.rename("components/" + name + "/css/" + name + ".css", "components/" + name + "/css/" + newname + ".css");
    scripts = fs.readFile("components/" + name + "/scripts", 'utf8', function(err, data) {
      scripts = data.replace("" + name + ".js", "" + newname + ".js");
      return fs.writeFile("components/" + name + "/scripts", scripts, 'utf8');
    });
    styles = fs.readFile("components/" + name + "/styles", 'utf8', function(err, data) {
      styles = data.replace("" + name + ".css", "" + newname + ".css");
      return fs.writeFile("components/" + name + "/styles", styles, 'utf8');
    });
    return fs.rename("components/" + name + "/js/" + name + ".coffee", "components/" + name + "/js/" + newname + ".coffee", function(err) {
      if (!(err != null)) {
        return childproc.exec("coffee -o components/" + name + "/js -c components/" + name + "/js/" + newname + ".coffee", function(er, o, e) {
          fs.rename("components/" + name, "components/" + newname);
          return callback(true);
        });
      } else {
        return callback(false, err);
      }
    });
  };

  everyone.now.publishComponent = function(name, user, repo, callback) {
    var options;
    if (path.exists("components/" + name + "/published")) {
      return callback('Already published.');
    } else {
      options = {
        cwd: './'
      };
      return childproc.exec("./publishplugin " + name + " " + user + " " + repo, function(err, stdout, stderr) {
        var msg, obj, pos;
        console.log(stderr);
        console.log(stdout);
        if (err != null) {
          console.log(util.inspect(err));
          return callback(err);
        } else {
          console.log('No error.');
          pos = stdout.indexOf('{');
          msg = stdout.substr(pos);
          obj = JSON.parse(msg);
          return callback(obj);
        }
      });
    }
  };

}).call(this);
