#!/bin/bash
# this way is best if you want to stay up to date
# or submit patches to node or npm

cd $HOME
if [ -d "$HOME/bin" ] ; then
  PATH="$PATH:$HOME/bin"
fi

mkdir $HOME/local
echo 'export PATH=$HOME/local/bin:$PATH' >> $HOME/.bashrc
. $HOME/.bashrc

# could also fork, and then clone your own fork instead of the official one

git clone git://github.com/joyent/node.git
cd node
./configure --prefix=$HOME/local
make install
cd ..

git clone git://github.com/isaacs/npm.git
cd npm
make install # or `make link` for bleeding edge
